apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: atta
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      location / {
        default_type application/json;
        return 200 "Aphirat Nimanussonkul";
      }
    }